slots:
  - index: 1
    tool_sn: "dispensing_ABC123"
    # tool_lifted_pose: [0.0, -0.164, 0.285, 0.0, 0.0, 0.0]
    # tool_attached_pose: [0.0, -0.164, 0.285, 0.0, 0.0, 0.0]
    # tool_slide_in_pose: [0.0, -0.164, 0.285, 0.0, 0.0, 0.0]
    launch_file: "dispensing_tool_launch.py"
  - index: 2
    tool_sn: "dispensing_DEF123"
    # tool_lifted_pose: [-0.249, -0.164, 0.285, 0.0, 0.0, 0.0]
    # tool_attached_pose: [0.0, -0.164, 0.285, 0.0, 0.0, 0.0]
    # tool_slide_in_pose: [0.0, -0.164, 0.285, 0.0, 0.0, 0.0]
    launch_file: "dispensing_tool_launch.py"
sim_bootup:
  - index: 1
    xacro_file: "dispensing_tool.srdf.xacro"
    tool_sn: "dispensing_ABC123"
    tool_type: "dispensing"
    tool_part_number: "ABC123"
    tool_part_revision: "A"
    material_part_number: "MAT123"
    material_part_revision: "A"
  - index: 2
    xacro_file: "dispensing_tool.srdf.xacro"
    tool_sn: "dispensing_DEF123"
    tool_type: "dispensing"
    tool_part_number: "DEF123"
    tool_part_revision: "A"
    material_part_number: "MAT456"
    material_part_revision: "A"