slots:
  - number: 1
    tool_sn: "abc123"
    tool_ref: "volumetric_dispenser"
    parameters:
      tool_sn: "abc123"
      tcp_frame_id: "tool0"
      tcp:
        - 0.0837
        - 0.0
        - -0.267
        - 1.570797
        - 0.0
        - 1.570797
      flowrate: 1.0
  - number: 2
    tool_sn: "def123"
    tool_ref: "volumetric_dispenser"
    parameters:
      tool_sn: "def123"
      tcp_frame_id: "tool0"
      tcp:
        - 0.0837
        - 0.0
        - -0.267
        - 1.570797
        - 0.0
        - 1.570797
      flowrate: 1.0
initial:
  - number: 1
    tool_sn: "abc123"
    tool_ref: "volumetric_dispenser"
  - number: 2
    tool_sn: "def123"
    tool_ref: "volumetric_dispenser"